feat: header, tabBar 컴포넌트 추가
prgrms-web-devcourse/Team_CherryBoys_MatchUs_FE pull request #3
Opened 2021-12-04 11:40 UTC by 94chl

### 헤더, 탭바 컴포넌트 추가
`Header`, `TabBar` 컴포넌트 추가 (`src/components/common`)
`Header`, `TabBar` 컴포넌트를 적용한 `DefaultTemplate` 추가(`src/components`)

- 라우팅 방법이 정해지면 `App.tsx` 파일 수정 필요
- 아이콘 사용을 위해 fontawesome 라이브러리 사용
-> 프로젝트에서 아이콘 사용을 위해서 해당 라이브러리를 쓸건지 논의필요
사용법 : [https://www.daleseo.com/react-font-awesome/](url)

2021-12-05 04:36 UTC, Kimbangg commented on src/components/common/Header/index.tsx
> +    history.go(-1);
아래와 같이 작성을 하면 위의 동작과 같은데 혹시 -1을 쓰신 이유가 있을까요?

```
const history = useHistory();
history.goBack()
```

2021-12-05 04:36 UTC, Kimbangg commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.16",
이미지가 많지 않다면, 라이브러리 대신 파일을 레포지터리 안에 두고 사용하면 어떨까요?

2021-12-05 04:36 UTC, Kimbangg commented on src/components/DefaultTemplate/DefaultTemplate.module.scss
> +  margin-top: 42px;
rem으로 단위를 통일 해야할 것 같습니다.

2021-12-05 04:36 UTC, Kimbangg commented on src/components/common/Header/index.tsx
> +    </div>
1) styles를 구조분해할당을 통해서 꺼내 사용하면 어떨까요?
2) scss 네이밍 컨벤션도 같이 고민해봅시다!

2021-12-05 04:36 UTC, Kimbangg commented on src/components/common/Header/Header.module.scss
> +    min-width: 4.2rem;
스타일을 적용하는 기준을 알려주기 위해 스타일 적용이 필요한 div에 className을 부여해서 사용해보면 어떨까요?

2021-12-05 04:36 UTC, Kimbangg commented on src/components/common/Header/index.tsx
> +        </button>
button을 눌렀을 때, 링크가 작동되는 개념이라면 아래와 같이 작성이 되어있을 때 `이 버튼을 누르면 어디로 가는구나!` 라고 조금 더 명확히 이해가 가능할 것 같은데 어떻게 생각하시나요? 

```
<Link to='login'>
    <Button>
</Link>
```

2021-12-05 04:36 UTC, Kimbangg commented on src/components/common/Header/index.tsx
> +          <Link to={'/login'}>로그인</Link>
중괄호 내부에 별도로 들어가는 변수 값이 없는데, {} 로 감싼 이유가 있을까요?

2021-12-05 04:36 UTC, Kimbangg commented on src/components/common/TabBar/index.tsx
> +        <Link to={'/'}><FontAwesomeIcon icon={faHome} /></Link>
중괄호 내부에 별도로 들어가는 변수 값이 없는데, {} 로 감싼 이유가 있을까요?

 - 리마인드 목적으로 작성하였습니다.

2021-12-05 04:49 UTC, Kimbangg commented on src/components/common/Header/Header.module.scss
> +    }
extensions에 stylelint 확장 프로그램을 설치하셔야 될 것 같아요 :)

포맷팅이 안된 상태로 SCSS가 넘어오는 것 같습니다!

2021-12-05 04:56 UTC, Kimbangg commented on src/components/common/Header/index.tsx
> +        <button onClick={handleGoBack}><FontAwesomeIcon icon={faChevronLeft} /></button>
button에 type이 없으면 Eslint에서 에러를 주는데, 로컬에서 확인이 안되는걸까요?

2021-12-05 04:56 UTC, Kimbangg commented on src/components/DefaultTemplate/index.tsx
> +import classNames from 'classnames';
사용 되지 않는 `classNames` 를 삭제하면 어떨까요?

2021-12-05 05:00 UTC, Kimbangg requested changes

2021-12-05 05:00 UTC, Kimbangg commented on src/App.tsx
> +import { Route, Switch } from 'react-router';
react-router는 native & web과 관련된 모든 기능들이 담겨있어서, web의 기능 중심으로 만들어진 react-router-dom을 패키지로 받아놨습니다.

`react-router` 를 `react-router-dom`으로 변경 부탁드려요.

2021-12-05 05:03 UTC, Kimbangg commented on src/App.tsx
> +import DefaultTemplate from '@/components/DefaultTemplate';
DefaultTemplate은 컴포넌트에 담겨있는데, 다른 폴더에서 적용했던 방식처럼 `index.ts` 로 파일들을 모아보내기 해서 사용해야 할 것 같아요.

`import DefaultTemplate from '@/components/DefaultTemplate';`  -> `import {DefaultTemplate} from @/components`

2021-12-05 05:06 UTC, Kimbangg reviewed
아래와 같이 작성하도록 컨벤션을 이야기 했었습니다 :)

```
- pages
   - Matches
     -  Matches.tsx
```

2021-12-05 06:17 UTC, 94chl commented on src/components/common/Header/index.tsx
> +    history.go(-1);
useHistory 쓰지 않고 바로 쓸 수 있고 익숙해서 history.go(-1) 썼습니다. 기능도 동일해서 상관없다고 생각합니다.

2021-12-05 06:19 UTC, 94chl commented on src/components/common/Header/index.tsx
> +    </div>
styles 구조분해할당 하면 클래스 이름을 2번이나 쓰게되서 코드가 불필요하게 길어질 것 같습니다

2021-12-05 06:22 UTC, 94chl commented on src/components/common/Header/Header.module.scss
> +    min-width: 4.2rem;
위의 scss 컨벤션과도 일맥상통하는 답변이 될거 같아서 한번에 쓰겠습니다.
scss가 해당 컴포넌트에만 적용되는데 모든 태그에 전부 클래스이름을 달아줄 필요가 있을까요?
전 태그에 클래스 이름을 달아주는 것은 해당 태그를 조작하기 위함이라고 생각하고 써왔습니다. 
그래서 태그를 조작할 때만 네이밍을 통해 컨트롤하면 되겠다고 판단했습니다.

2021-12-05 06:23 UTC, 94chl commented on src/components/common/Header/index.tsx
> +        </button>
옹 저랑 완전히 반대군요 😃 
전 결국 버튼을 누르면 링크가 이동한다는 생각에 항상 버튼 속에 a태그를 달았었는데 흥미롭네용

2021-12-05 07:46 UTC, Kimbangg commented on src/components/common/Header/Header.module.scss
> +    min-width: 4.2rem;
모든 태그가 `div` 여도 괜찮다면, 저도 용스톤의 의견에 동의합니다.
다만, 이 코멘트를 달았을 때 먼저 들었던 생각은 모든 태그를 div로 쓰이면 `semantic`하게 사용이 잘 되고 있는건가? 라는 의문을 가지게 되었고, 이후에 스타일을 먹이는 대상과 이유가 명확하면 좋겠다는 생각을 가지게 되었네요.

저의 경우, 이러한 생각들이  `history.goBack()`  코멘트에서도 말씀 드렸던 부분에도 적용이 되었다고 생각합니다.
history.go(-1) 자체도 뒤로 가는 행동 임을 추측할 수 있지만 제가 느끼기에는 goBack() 함수를 쓰는게 어떤 행동을 하려고 하는지 더 명확하게 느껴졌다고 생각합니다.

결과적으로는 `명시적인 코드` 를 작성하는 궁극적인 목표는 유지/보수의 관점이라고 생각합니다. 
현재는 어떤 코드인지 명확히 이해가 가능하고, 필요에 따라 수정이 가능하겠지만 오랜 시간이 지나서 본다면 어떨까요?

이러한 부분들에 대해서 용스톤의 의견이 궁금합니다

2021-12-05 07:47 UTC, Kimbangg commented on src/components/common/Header/index.tsx
> +        </button>
이 부분은 팀원들과 함께 이야기해보죠 :)

2021-12-05 07:48 UTC, 94chl commented on src/components/common/Header/index.tsx
> +        <button onClick={handleGoBack}><FontAwesomeIcon icon={faChevronLeft} /></button>
린트 적용이 안되고 있었네요 체크해봐야겠네요

2021-12-05 07:50 UTC, Kimbangg commented on src/components/common/Header/index.tsx
> +        <button onClick={handleGoBack}><FontAwesomeIcon icon={faChevronLeft} /></button>
formatOnSave가 설정에 들어가있는지 확인해보시면 좋을 것 같아요

2021-12-05 11:27 UTC, 94chl commented on src/components/common/Header/Header.module.scss
> +    min-width: 4.2rem;
확실히 12가 있는 말입니다. 피드백 적극 수용합니다.
개발 최대 난제 이름 짓기가 고민이겠군요 ㅋㅋ

2021-12-05 14:59 UTC, HongJungKim-dev approved these changes
고생많으셨습니다~
크게는 다음 사항들 변경후 커밋하시면 될것 같습니다!
동현님과 제가 남긴 리뷰 중 크게 수정해야할 부분을 리마인드하는 차원에서 보기 쉽게 정리해봤습니다.

* stylelint 설치
* 린트적용
* react-router를 react-router-dom로 변경
* px-> rem으로 변경
* fortawesome 라이브러리 설치가 아닌 다른 방법으로 변경

2021-12-05 14:59 UTC, HongJungKim-dev commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.16",
fontawesome은 라이브러리 install하지 않고 class로 사용할 수 있던것으로 기억하는데 그러한 방법은 fortawesome에서 불가능할까요?

2021-12-05 14:59 UTC, HongJungKim-dev commented on src/components/DefaultTemplate/DefaultTemplate.module.scss
> +  margin-top: 42px;
동감합니다! 반응형 작업을 위하여 rem으로 통일하는것이 좋다고 얘기하였던것으로 기억합니다. 추후 변경하고자 하셨던것 같은데 그러면 나중에 하기 힘든것 같아서요!
@Kimbangg rem으로 작성하기 위하여서는 [[링크](http://pxtoem.com/)]와 같은 사이트에서 px를 rem으로 변환후 rem을 작성하면 될까요?

2021-12-05 14:59 UTC, HongJungKim-dev commented on src/components/common/Header/index.tsx
> +        </button>
오  저는 보통 history push를 이용하였습니다.

2021-12-05 15:34 UTC, HongJungKim-dev commented on src/components/common/Header/index.tsx
> +        <button onClick={handleGoBack}><FontAwesomeIcon icon={faChevronLeft} /></button>
main에서 branch 따셨는데 왜 적용이 안된것인가요?

2021-12-06 02:28 UTC, 94chl commented on src/components/common/Header/index.tsx
> +        <button onClick={handleGoBack}><FontAwesomeIcon icon={faChevronLeft} /></button>
vsc 확장 설정에서 타스를 추가 안했더라고요;;

2021-12-06 02:38 UTC, 94chl commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.16",
맞아요 i 태그도 제공합니다. 그런데이거 쓰려면 cdn 연결을 해줘하는데, 리액트는 루트html이 없더라고요. 그래서 라이브러리 썼습니다

2021-12-06 02:43 UTC, 94chl commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.16",
cdn 걍 `return`의 `html`에 박아넣어도 되는군요;; 몰랐다;; 라이브러리말고 cdn으로 가겠습니다

2021-12-06 13:51 UTC, Kimbangg approved these changes
LGTM 👍🏻

2021-12-06 14:10 UTC, merged